### ISSUE TITLE
NullColor causes problems with wxpython2.9

### ISSUE THREAD

**Issue by mikeferguson** [vanadiumlabs/pypose#1]
i have a problem with starting pypose
i download python2.7,wxpython2.9 and pyserial
i install them when i try to start pypose i had this message

Traceback (most recent call last):
File "C:\Users\abdo\Desktop\pypose\arbotix-pypose-v1.1-beta1\pypose\PyPose.py", line 373, in <module>
frame = editor()
File "C:\Users\abdo\Desktop\pypose\arbotix-pypose-v1.1-beta1\pypose\PyPose.py", line 136, in **init**
self.SetBackgroundColour(wx.NullColor) # wx.SystemSettings.GetColour(wx.SYS_COLOUR_MENU)
AttributeError: 'module' object has no attribute 'NullColor'

(imported from https://code.google.com/p/arbotix/issues/detail?id=27)

**Comment by hokster7** [comment]
+1 it sucks not to be able to run PyPose on a Mac easily. All I want to do with it is set the ids of my servos!

**Comment by mikeferguson** [comment]
Could you pull the latest and see if it works for you?

**Comment by hokster7** [comment]
I think #6 could be related to 2.9; so even if the `NullColor` fix does prevent that particular error we should work to resolve all errors relating to wxPython 2.9 before closing this issue.

I say 'I think' because I couldn't get PyPose running with `wxPython2.8-osx-unicode-universal-py2.7.pkg` downloaded from the site, which would tell me whether it's a 2.9 specific problem or not.

**Comment by mikeferguson** [comment]
A single ticket for all 2.9 issues is really too broad, individual tickets are more targeted and easily serviced. It appears this patch does fix the specific problem this ticket is focused on -- I've updated the description accordingly to properly scope it, and am closing.
